2025-08-10 17:18:33,253 (4500/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-08-10 17:18:33,253 (4500/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-08-10 17:21:13,121 (4861/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-08-10 17:21:13,121 (4861/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-08-10 17:21:13,122 (4861/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: background
2025-08-10 17:22:33,369 (4861/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE table', error: SyntaxError('syntax error at end of input\nLINE 1: CREATE table\n                    ^')
2025-08-10 17:22:33,370 (4861/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at end of input\nLINE 1: CREATE table\n                    ^\n'
2025-08-10 17:22:40,411 (4861/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE TABLE test', error: SyntaxError('syntax error at end of input\nLINE 1: CREATE TABLE test\n                         ^')
2025-08-10 17:22:40,412 (4861/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at end of input\nLINE 1: CREATE TABLE test\n                         ^\n'
2025-08-10 17:22:42,576 (4861/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE TABLE test', error: SyntaxError('syntax error at end of input\nLINE 1: CREATE TABLE test\n                         ^')
2025-08-10 17:22:42,577 (4861/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at end of input\nLINE 1: CREATE TABLE test\n                         ^\n'
2025-08-10 17:22:44,199 (4861/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE TABLE test', error: SyntaxError('syntax error at end of input\nLINE 1: CREATE TABLE test\n                         ^')
2025-08-10 17:22:44,201 (4861/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at end of input\nLINE 1: CREATE TABLE test\n                         ^\n'
2025-08-10 17:22:50,165 (4861/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE TABLE test', error: SyntaxError('syntax error at end of input\nLINE 1: CREATE TABLE test\n                         ^')
2025-08-10 17:22:50,166 (4861/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at end of input\nLINE 1: CREATE TABLE test\n                         ^\n'
2025-08-10 17:23:09,073 (4861/MainThread) pgcli.pgexecute ERROR - sql: 'SHOW table', error: SyntaxError('syntax error at or near "table"\nLINE 1: SHOW table\n             ^')
2025-08-10 17:23:09,073 (4861/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "table"\nLINE 1: SHOW table\n             ^\n'
2025-08-10 17:23:13,478 (4861/MainThread) pgcli.pgexecute ERROR - sql: 'SHOW tables', error: UndefinedObject('unrecognized configuration parameter "tables"')
2025-08-10 17:23:13,480 (4861/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedObject: unrecognized configuration parameter "tables"\n'
2025-08-10 17:23:54,979 (4861/MainThread) pgcli.pgexecute ERROR - sql: 'q', error: SyntaxError('syntax error at or near "q"\nLINE 1: q\n        ^')
2025-08-10 17:23:54,980 (4861/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "q"\nLINE 1: q\n        ^\n'
2025-08-10 17:24:47,893 (5294/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-08-10 17:24:47,893 (5294/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-08-10 17:24:47,893 (5294/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: background
2025-08-10 19:23:00,878 (8117/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-08-10 19:23:00,879 (8117/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-08-10 19:23:00,880 (8117/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: background
2025-08-10 19:23:52,201 (8117/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE TABLE products (', error: SyntaxError('syntax error at end of input\nLINE 1: CREATE TABLE products (\n                               ^')
2025-08-10 19:23:52,205 (8117/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at end of input\nLINE 1: CREATE TABLE products (\n                               ^\n'
2025-08-10 19:24:00,944 (8117/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE TABLE products (\\', error: SyntaxError('syntax error at or near "\\"\nLINE 1: CREATE TABLE products (\\\n                               ^')
2025-08-10 19:24:00,945 (8117/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: CREATE TABLE products (\\\n                               ^\n'
2025-08-11 13:13:00,493 (17747/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-08-11 13:13:00,494 (17747/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-08-11 13:13:00,495 (17747/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: background
2025-08-11 13:13:02,952 (17747/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 181, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 230, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/psycopg/connection.py", line 749, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: fe_sendauth: no password supplied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/pgcli/main.py", line 670, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 181, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 230, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/psycopg/connection.py", line 749, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: FATAL:  password authentication failed for user "postgres"\nconnection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "postgres"\n'
2025-08-11 13:13:08,993 (17762/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-08-11 13:13:08,993 (17762/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-08-11 13:13:08,994 (17762/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: background
2025-08-11 14:47:47,242 (3793/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-08-11 14:47:47,243 (3793/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-08-11 14:47:47,244 (3793/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: background
2025-08-12 09:55:55,788 (4820/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-08-12 09:55:55,789 (4820/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-08-12 09:55:55,790 (4820/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: background
2025-08-12 10:35:29,054 (4820/MainThread) pgcli.pgexecute ERROR - sql: 'EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) DESCRIBE appointments', error: SyntaxError('syntax error at or near "DESCRIBE"\nLINE 1: ...N (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) DESCRIBE a...\n                                                             ^')
2025-08-12 10:35:29,061 (4820/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "DESCRIBE"\nLINE 1: ...N (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) DESCRIBE a...\n                                                             ^\n'
2025-08-12 10:35:44,327 (4820/MainThread) pgcli.pgexecute ERROR - sql: 'EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) DESCRIBE appointments', error: SyntaxError('syntax error at or near "DESCRIBE"\nLINE 1: ...N (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) DESCRIBE a...\n                                                             ^')
2025-08-12 10:35:44,330 (4820/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "DESCRIBE"\nLINE 1: ...N (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) DESCRIBE a...\n                                                             ^\n'
2025-08-12 10:37:24,980 (4820/MainThread) pgcli.pgexecute ERROR - sql: 'EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) SHOW TABLE appointments', error: SyntaxError('syntax error at or near "SHOW"\nLINE 1: ...N (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) SHOW TABLE...\n                                                             ^')
2025-08-12 10:37:24,982 (4820/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "SHOW"\nLINE 1: ...N (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) SHOW TABLE...\n                                                             ^\n'
2025-08-12 10:37:46,443 (4820/MainThread) pgcli.pgexecute ERROR - sql: 'EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) DESCRIBE appointments', error: SyntaxError('syntax error at or near "DESCRIBE"\nLINE 1: ...N (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) DESCRIBE a...\n                                                             ^')
2025-08-12 10:37:46,445 (4820/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "DESCRIBE"\nLINE 1: ...N (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) DESCRIBE a...\n                                                             ^\n'
2025-08-12 10:38:19,313 (4820/MainThread) pgcli.pgexecute ERROR - sql: 'EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) \\d appointments', error: SyntaxError('syntax error at or near "\\"\nLINE 1: ...N (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) \\d appoint...\n                                                             ^')
2025-08-12 10:38:19,315 (4820/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: ...N (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) \\d appoint...\n                                                             ^\n'
2025-08-12 10:38:31,957 (7857/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-08-12 10:38:31,958 (7857/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-08-12 10:38:31,959 (7857/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: background
2025-08-12 11:44:39,743 (7857/MainThread) pgcli.pgexecute ERROR - sql: "select event_name,durations from events where duration > '2 hours'", error: UndefinedColumn('column "durations" does not exist\nLINE 1: select event_name,durations from events where duration > \'2 ...\n                          ^\nHINT:  Perhaps you meant to reference the column "events.duration".')
2025-08-12 11:44:39,746 (7857/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedColumn: column "durations" does not exist\nLINE 1: select event_name,durations from events where duration > \'2 ...\n                          ^\nHINT:  Perhaps you meant to reference the column "events.duration".\n'
2025-08-12 12:18:09,237 (12451/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-08-12 12:18:09,237 (12451/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-08-12 12:18:09,238 (12451/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: background
2025-08-12 13:35:34,660 (12451/MainThread) pgcli.pgexecute ERROR - sql: 'q\\q', error: SyntaxError('syntax error at or near "q"\nLINE 1: q\\q\n        ^')
2025-08-12 13:35:34,663 (12451/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "q"\nLINE 1: q\\q\n        ^\n'
2025-08-16 01:56:45,693 (30817/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-08-16 01:56:45,694 (30817/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-08-16 01:56:45,695 (30817/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: background
2025-08-16 01:56:49,223 (30817/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 181, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 230, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/psycopg/connection.py", line 749, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: fe_sendauth: no password supplied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/pgcli/main.py", line 670, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 181, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 230, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/psycopg/connection.py", line 749, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: FATAL:  password authentication failed for user "postgres"\nconnection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "postgres"\n'
2025-08-16 01:56:51,353 (30837/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-08-16 01:56:51,353 (30837/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-08-16 01:56:51,354 (30837/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: background
2025-08-16 02:33:56,407 (30837/MainThread) pgcli.pgexecute ERROR - sql: '/q', error: SyntaxError('syntax error at or near "/"\nLINE 1: /q\n        ^')
2025-08-16 02:33:56,411 (30837/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "/"\nLINE 1: /q\n        ^\n'
2025-08-18 14:57:04,505 (65160/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-08-18 14:57:04,506 (65160/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-08-18 14:57:04,507 (65160/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: background
